import type { Bank } from '@/shared/types';

// Mock catalogue of banks the user has accounts with / can apply to.
// Rates reflect realistic 2026 RU consumer-loan ranges. Replace with bank APIs later.

export const BANKS: Bank[] = [
  {
    id: 'sber',
    name: 'Сбербанк',
    short: 'СБ',
    color: '#21A038',
    rateFrom: 21.9,
    rateBase: 27.9,
    maxAmount: 5_000_000,
    minTermMonths: 3,
    maxTermMonths: 60,
    requiresIncomeProof: false,
    insuranceAvailable: true,
    earlyRepaymentFree: true,
    approvalTime: '2 минуты',
    rating: 4.6,
    isUserBank: true,
    features: [
      'Зарплатным клиентам ставка от 21.9%',
      'Решение онлайн без справок до 1 млн ₽',
      'Досрочное погашение без комиссии',
      'Страхование снижает ставку на 6 п.п.',
    ],
  },
  {
    id: 'tbank',
    name: 'Т-Банк',
    short: 'Т',
    color: '#FFDD2D',
    rateFrom: 23.5,
    rateBase: 29.9,
    maxAmount: 3_000_000,
    minTermMonths: 3,
    maxTermMonths: 60,
    requiresIncomeProof: false,
    insuranceAvailable: true,
    earlyRepaymentFree: true,
    approvalTime: '1 минута',
    rating: 4.7,
    isUserBank: true,
    features: [
      'Полностью онлайн, доставка карты курьером',
      'Первое решение за 1 минуту',
      'Гибкий график платежей',
      'Кешбэк на платежи по кредиту',
    ],
  },
  {
    id: 'vtb',
    name: 'ВТБ',
    short: 'ВТ',
    color: '#0A2896',
    rateFrom: 22.4,
    rateBase: 28.5,
    maxAmount: 7_000_000,
    minTermMonths: 6,
    maxTermMonths: 84,
    requiresIncomeProof: true,
    insuranceAvailable: true,
    earlyRepaymentFree: true,
    approvalTime: '1 день',
    rating: 4.3,
    features: [
      'Крупные суммы до 7 млн ₽',
      'Длинный срок до 7 лет',
      'Требуется подтверждение дохода (2-НДФЛ)',
      'Надбавка 3 п.п. без личного страхования',
    ],
  },
  {
    id: 'alfa',
    name: 'Альфа-Банк',
    short: 'А',
    color: '#EF3124',
    rateFrom: 23.9,
    rateBase: 30.9,
    maxAmount: 4_000_000,
    minTermMonths: 3,
    maxTermMonths: 60,
    requiresIncomeProof: false,
    insuranceAvailable: true,
    earlyRepaymentFree: true,
    approvalTime: '5 минут',
    rating: 4.5,
    isUserBank: true,
    features: [
      'Кредитные каникулы до 2 месяцев',
      'Без справок до 1.5 млн ₽',
      'Ставка зависит от кредитной истории',
      'Страхование жизни обязательно для мин. ставки',
    ],
  },
  {
    id: 'gazprom',
    name: 'Газпромбанк',
    short: 'ГП',
    color: '#1B458F',
    rateFrom: 21.5,
    rateBase: 27.0,
    maxAmount: 5_000_000,
    minTermMonths: 6,
    maxTermMonths: 84,
    requiresIncomeProof: true,
    insuranceAvailable: true,
    earlyRepaymentFree: false,
    approvalTime: '2 дня',
    rating: 4.2,
    features: [
      'Одна из самых низких ставок на рынке',
      'Требуется справка о доходах',
      'Комиссия при досрочном погашении в первые 3 мес.',
      'Скидка для сотрудников компаний-партнёров',
    ],
  },
  {
    id: 'raif',
    name: 'Райффайзен',
    short: 'РФ',
    color: '#FEE600',
    rateFrom: 24.9,
    rateBase: 31.5,
    maxAmount: 3_000_000,
    minTermMonths: 12,
    maxTermMonths: 60,
    requiresIncomeProof: true,
    insuranceAvailable: true,
    earlyRepaymentFree: true,
    approvalTime: '1 день',
    rating: 4.4,
    features: [
      'Премиальный сервис и поддержка 24/7',
      'Минимальный срок от 1 года',
      'Подтверждение дохода обязательно',
      'Фиксированная ставка на весь срок',
    ],
  },
];

export const getUserBanks = () => BANKS.filter(b => b.isUserBank);
